server:
  port: 80

#配置链路追踪地址
spring:
  zipkin:
    base-url: http://192.168.6.200:9411/
    sender:
      type: web

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"   #允许所有地址来源跨域
            allowedMethods: "*"   #允许所有请求方式跨域
            allowedHeaders: "*"   #允许所有请求头跨域
            allowCredentials: true   #允许带一些安全标志跨域 比如：Cookie

      #所有的网关路由规则
      routes:
        - id: product_route   #以/admin/product开头的所有请求都lb(loadbalancer)转给service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com