server:
  port: 6000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
app:
  thread-pool:
    core: 2
    max: 4
    queue-size: 1000
    keep-alive-time: 300

#暴漏所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"